export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const GET_COURSE_DETAILS = 'GET_COURSE_DETAILS';
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS';
export const COURSE_DETAILS_FAILED = 'COURSE_DETAILS_FAILED';

export const GET_TUTORIAL_DETAILS = 'GET_TUTORIAL_DETAILS';
export const TUTORIAL_DETAILS_SUCCESS = 'TUTORIAL_DETAILS_SUCCESS';
export const TUTORIAL_DETAILS_FAILED = 'TUTORIAL_DETAILS_FAILED';

export const GET_SOURCES = 'GET_SOURCES';
export const SOURCES_SUCCESS = 'SOURCES_SUCCESS';
export const SOURCES_FAILED = 'SOURCES_FAILED';


